Feature g9 map object edition
PSW-2020-ORG4/HealthcareSystem pull request #31
Opened 2020-11-06 21:54 UTC by kmilena98

Adding possibility to edit map object

2020-11-06 22:18 UTC, vlaksi requested changes

2020-11-06 22:18 UTC, vlaksi commented on HealthcareSystem/GraphicalEditor/MainWindow.xaml.cs
> +                handler(this, e);
Give a more descriptive name for 'e'  or do this:

```sh
    handler(this,  new PropertyChangedEventArgs(propertyName));
```

2020-11-06 22:18 UTC, vlaksi commented on HealthcareSystem/GraphicalEditor/MainWindow.xaml.cs
>              //saveMap();
Why is dead code here?  Try to avoid dead code.

2020-11-06 22:18 UTC, vlaksi commented on HealthcareSystem/GraphicalEditor/MainWindow.xaml.cs
> +            }
What is this doing?

2020-11-06 22:19 UTC, milana-todorovic commented
This branch was separated from a feature branch instead of develop, so it can't really be merged to develop like this according to our workflow. One possible solution would be to delete this branch and pull request, make a new branch from develop once feature-g8-display-all-information is merged, and then copy the changes you made here to that new branch. Another option would be to not merge the feature-g8-display-all-information branch and merge this instead, but I'd rather not do that since commits up to the last one have already been reviewed on the other pull request. The third option is to close this pull request, merge this branch into feature-g8-display-all-information, and have this last commit reviewed on that pull request as well. Whichever of those works for you is fine.

2020-11-06 22:58 UTC, kmilena98 commented on HealthcareSystem/GraphicalEditor/MainWindow.xaml.cs
> +            }
i didnt finished it yet

2020-11-06 23:20 UTC, VasilijeBursac commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) g10: Change additional information (description, working hours,...)](https://trello.com/c/VHHUGlJb/10-3-g10-change-additional-information-description-working-hours)

2020-11-06 23:21 UTC, VasilijeBursac commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) g9: Change basic information (name)](https://trello.com/c/omjRBFsz/9-3-g9-change-basic-information-name)

2020-11-07 00:25 UTC, kmilena98 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) g9: Change basic information (name)](https://trello.com/c/omjRBFsz/9-3-g9-change-basic-information-name)

2020-11-07 00:26 UTC, kmilena98 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) g9: Change basic information (name)](https://trello.com/c/omjRBFsz/9-3-g9-change-basic-information-name)

2020-11-07 16:28 UTC, vlaksi commented
@VasilijeBursac @kmilena98 what are you decide with this branch? Milana gives you a proposal above.

2020-11-07 23:27 UTC, VasilijeBursac commented
> @VasilijeBursac @kmilena98 what are you decide with this branch? Milana gives you a proposal above.

@vlaksi Milena will solve that with branches. She can give you more details about this branch because she worked on it.

2020-11-08 16:07 UTC, milana-todorovic commented
Closed without merge because of workflow issues. Changes moved to branch feature-g9-edition.

2020-11-08 16:07 UTC, closed without merging