feat[w2.4]: basic search for Examinations and Therapies
PSW-2020-ORG4/HealthcareSystem pull request #80
Opened 2020-11-26 23:51 UTC by jelenabudisa

First commit is irrelevant because it was made due to an error.
I added methods for basic search of examinations and therapies for a patient.

2020-11-27 00:04 UTC, jelenabudisa commented
![](https://github.trello.services/images/mini-trello-icon.png) [(8) W2.4 As a patient I want to search documentation about my recipes and examination reports so that I could find information I need.](https://trello.com/c/bKGyskUq/23-8-w24-as-a-patient-i-want-to-search-documentation-about-my-recipes-and-examination-reports-so-that-i-could-find-information-i-ne)

2020-11-27 15:51 UTC, Pufke requested changes

2020-11-27 15:51 UTC, Pufke commented on HealthcareSystem/Backend/Service/DrugAndTherapy/TherapyService.cs
> +        public List<Therapy> GetTherapiesByExaminationSearch(List<Therapy> therapies, string startDate, string endDate, string doctorSurname, string drugName)
A method contains too many lines of code. Generally, any method longer than ten lines should make you start asking questions.

If you feel the need to comment on something inside a method, you should take this code and put it in a new method. Even a single line can and should be split off into a separate method, if it requires explanations. And if the method has a descriptive name, nobody will need to look at the code to see what it does.

To reduce the length of a method body, use Extract Method ( https://refactoring.guru/extract-method ).

2020-11-27 15:51 UTC, Pufke commented on HealthcareSystem/Backend/Service/ExaminationAndPatientCard/ExaminationService.cs
> +        public List<Examination> GetExaminationsByPatientSearch(List<Examination> examinations, string startDate, string endDate, string doctorSurname, string anamesis)
Same problem

2020-11-27 15:51 UTC, Pufke commented on HealthcareSystem/PatientWebApp/DTOs/ExaminationDTO.cs
> +        public string DateAndTime { get; set; }
Why string instead of DateTime?

2020-11-27 15:51 UTC, Pufke commented on HealthcareSystem/PatientWebApp/DTOs/TherapyDTO.cs
> +        public string StartDate { get; set; }
Same, why string ?

2020-11-27 16:33 UTC, anciz reviewed
Generally, well done, you did much work!
Just few changes and it will be great.

2020-11-27 16:33 UTC, anciz commented on HealthcareSystem/PatientWebApp/wwwroot/html/search_documentation.html
>                  </tr>
Will you use this 84th line of code?
My suggestion is to delete it if you won't use it.
And please if it is not a problem, change Serch to Search in comment (I know it was accidentally).

2020-11-27 16:37 UTC, anciz commented on HealthcareSystem/Backend/Repository/TherapyRepository/MySqlTherapyRepository/MySqlTherapyRepository.cs
> +        }
Also, what will be with this? Will it be solved?

2020-11-28 18:50 UTC, milana-todorovic reviewed
Since the advanced search has been implemented and tested, I suggest using that to implement this as well (as far as I'm aware the search uses the same parameters, but that the advanced just has operators added). I suggest either just using the advanced search endpoint and forming the DTO appropriately (all operators are AND), or making a new endpoint and using the specification classes.

2020-11-29 15:30 UTC, milana-todorovic requested changes
There are issues with the project build, I assume because of merge mistakes. Since as far as I know you'll be using the endpoint for advanced search so the only actually relevant files on this branch are the html and JavaScript files, I believe that opening a new branch and just copying that will be easier than trying to fix this one and merge it correctly.

2020-11-29 17:00 UTC, milana-todorovic commented
Closed without merge because there weren't many relevant new changes on this branch and there were merge issues. All relevant changes were moved to PR #90 instead.

2020-11-29 17:00 UTC, closed without merging